export interface Preset {
  id: string
  name: string
  icon: string
  description: string
  packages: { name: string; cask: boolean }[]
}

export const presets: Preset[] = [
  {
    id: 'web-dev',
    name: 'Web Developer',
    icon: '🌐',
    description: 'Frontend & backend essentials',
    packages: [
      { name: 'node', cask: false },
      { name: 'git', cask: false },
      { name: 'gh', cask: false },
      { name: 'pnpm', cask: false },
      { name: 'typescript', cask: false },
      { name: 'deno', cask: false },
      { name: 'yarn', cask: false },
      { name: 'jq', cask: false },
      { name: 'httpie', cask: false },
      { name: 'visual-studio-code', cask: true },
      { name: 'iterm2', cask: true },
      { name: 'figma', cask: true },
      { name: 'firefox', cask: true },
      { name: 'google-chrome', cask: true },
      { name: 'postman', cask: true },
    ],
  },
  {
    id: 'ios-dev',
    name: 'iOS Developer',
    icon: '📱',
    description: 'Swift & Xcode tooling',
    packages: [
      { name: 'git', cask: false },
      { name: 'gh', cask: false },
      { name: 'cocoapods', cask: false },
      { name: 'swiftlint', cask: false },
      { name: 'swiftformat', cask: false },
      { name: 'xcbeautify', cask: false },
      { name: 'fastlane', cask: false },
      { name: 'carthage', cask: false },
      { name: 'iterm2', cask: true },
      { name: 'sf-symbols', cask: true },
      { name: 'proxyman', cask: true },
      { name: 'xcodes-app', cask: true },
    ],
  },
  {
    id: 'data-science',
    name: 'Data Science',
    icon: '📊',
    description: 'Python, R & data tools',
    packages: [
      { name: 'python@3.13', cask: false },
      { name: 'pyenv', cask: false },
      { name: 'pipx', cask: false },
      { name: 'r', cask: false },
      { name: 'jupyterlab', cask: false },
      { name: 'git', cask: false },
      { name: 'jq', cask: false },
      { name: 'sqlite', cask: false },
      { name: 'postgresql@16', cask: false },
      { name: 'visual-studio-code', cask: true },
      { name: 'docker-desktop', cask: true },
      { name: 'rstudio', cask: true },
    ],
  },
  {
    id: 'devops',
    name: 'DevOps / SRE',
    icon: '🔧',
    description: 'Containers, cloud & infra',
    packages: [
      { name: 'git', cask: false },
      { name: 'gh', cask: false },
      { name: 'awscli', cask: false },
      { name: 'terraform', cask: false },
      { name: 'kubernetes-cli', cask: false },
      { name: 'helm', cask: false },
      { name: 'k9s', cask: false },
      { name: 'ansible', cask: false },
      { name: 'jq', cask: false },
      { name: 'yq', cask: false },
      { name: 'curl', cask: false },
      { name: 'wget', cask: false },
      { name: 'tmux', cask: false },
      { name: 'docker-desktop', cask: true },
      { name: 'iterm2', cask: true },
    ],
  },
  {
    id: 'designer',
    name: 'Designer',
    icon: '🎨',
    description: 'Design, prototyping & creative',
    packages: [
      { name: 'git', cask: false },
      { name: 'imagemagick', cask: false },
      { name: 'figma', cask: true },
      { name: 'sketch', cask: true },
      { name: 'zeplin', cask: true },
      { name: 'blender', cask: true },
      { name: 'inkscape', cask: true },
      { name: 'gimp', cask: true },
      { name: 'rectangle', cask: true },
      { name: 'notion', cask: true },
    ],
  },
  {
    id: 'terminal-power',
    name: 'Terminal Power User',
    icon: '⚡',
    description: 'Shell productivity & CLI tools',
    packages: [
      { name: 'git', cask: false },
      { name: 'neovim', cask: false },
      { name: 'tmux', cask: false },
      { name: 'ripgrep', cask: false },
      { name: 'fd', cask: false },
      { name: 'bat', cask: false },
      { name: 'eza', cask: false },
      { name: 'fzf', cask: false },
      { name: 'zoxide', cask: false },
      { name: 'starship', cask: false },
      { name: 'htop', cask: false },
      { name: 'tldr', cask: false },
      { name: 'tree', cask: false },
      { name: 'jq', cask: false },
      { name: 'lazygit', cask: false },
      { name: 'git-delta', cask: false },
    ],
  },
  {
    id: 'rust-dev',
    name: 'Rust Developer',
    icon: '🦀',
    description: 'Rust toolchain & ecosystem',
    packages: [
      { name: 'rustup', cask: false },
      { name: 'git', cask: false },
      { name: 'gh', cask: false },
      { name: 'cmake', cask: false },
      { name: 'protobuf', cask: false },
      { name: 'llvm', cask: false },
      { name: 'sccache', cask: false },
      { name: 'ripgrep', cask: false },
      { name: 'fd', cask: false },
      { name: 'bat', cask: false },
      { name: 'hyperfine', cask: false },
      { name: 'tokei', cask: false },
      { name: 'visual-studio-code', cask: true },
      { name: 'iterm2', cask: true },
    ],
  },
  {
    id: 'go-dev',
    name: 'Go Developer',
    icon: '🐹',
    description: 'Go toolchain & common tools',
    packages: [
      { name: 'go', cask: false },
      { name: 'golangci-lint', cask: false },
      { name: 'protobuf', cask: false },
      { name: 'git', cask: false },
      { name: 'gh', cask: false },
      { name: 'jq', cask: false },
      { name: 'delve', cask: false },
      { name: 'grpcurl', cask: false },
      { name: 'visual-studio-code', cask: true },
      { name: 'goland', cask: true },
      { name: 'docker-desktop', cask: true },
      { name: 'iterm2', cask: true },
    ],
  },
]

export function usePresets() {
  return { presets }
}
