export interface Preset {
  id: string
  name: string
  icon: string
  description: string
  packages: { name: string; cask: boolean }[]
}

export const presets: Preset[] = [
  {
    id: 'web-dev',
    name: 'Web Developer',
    icon: '🌐',
    description: 'Frontend & backend essentials',
    packages: [
      { name: 'node', cask: false },
      { name: 'git', cask: false },
      { name: 'gh', cask: false },
      { name: 'pnpm', cask: false },
      { name: 'typescript', cask: false },
      { name: 'deno', cask: false },
      { name: 'yarn', cask: false },
      { name: 'jq', cask: false },
      { name: 'httpie', cask: false },
      { name: 'visual-studio-code', cask: true },
      { name: 'iterm2', cask: true },
      { name: 'figma', cask: true },
      { name: 'firefox', cask: true },
      { name: 'google-chrome', cask: true },
      { name: 'postman', cask: true },
    ],
  },
  {
    id: 'ios-dev',
    name: 'iOS Developer',
    icon: '📱',
    description: 'Swift & Xcode tooling',
    packages: [
      { name: 'git', cask: false },
      { name: 'gh', cask: false },
      { name: 'cocoapods', cask: false },
      { name: 'swiftlint', cask: false },
      { name: 'swiftformat', cask: false },
      { name: 'xcbeautify', cask: false },
      { name: 'fastlane', cask: false },
      { name: 'carthage', cask: false },
      { name: 'iterm2', cask: true },
      { name: 'sf-symbols', cask: true },
      { name: 'proxyman', cask: true },
      { name: 'xcodes-app', cask: true },
    ],
  },
  {
    id: 'data-science',
    name: 'Data Science',
    icon: '📊',
    description: 'Python, R & data tools',
    packages: [
      { name: 'python@3.13', cask: false },
      { name: 'pyenv', cask: false },
      { name: 'pipx', cask: false },
      { name: 'r', cask: false },
      { name: 'jupyterlab', cask: false },
      { name: 'git', cask: false },
      { name: 'jq', cask: false },
      { name: 'sqlite', cask: false },
      { name: 'postgresql@16', cask: false },
      { name: 'visual-studio-code', cask: true },
      { name: 'docker-desktop', cask: true },
      { name: 'rstudio', cask: true },
    ],
  },
  {
    id: 'devops',
    name: 'DevOps / SRE',
    icon: '🔧',
    description: 'Containers, cloud & infra',
    packages: [
      { name: 'git', cask: false },
      { name: 'gh', cask: false },
      { name: 'awscli', cask: false },
      { name: 'terraform', cask: false },
      { name: 'kubernetes-cli', cask: false },
      { name: 'helm', cask: false },
      { name: 'k9s', cask: false },
      { name: 'ansible', cask: false },
      { name: 'jq', cask: false },
      { name: 'yq', cask: false },
      { name: 'curl', cask: false },
      { name: 'wget', cask: false },
      { name: 'tmux', cask: false },
      { name: 'docker-desktop', cask: true },
      { name: 'iterm2', cask: true },
    ],
  },
  {
    id: 'designer',
    name: 'Designer',
    icon: '🎨',
    description: 'Design, prototyping & creative',
    packages: [
      { name: 'git', cask: false },
      { name: 'imagemagick', cask: false },
      { name: 'figma', cask: true },
      { name: 'sketch', cask: true },
      { name: 'zeplin', cask: true },
      { name: 'blender', cask: true },
      { name: 'inkscape', cask: true },
      { name: 'gimp', cask: true },
      { name: 'rectangle', cask: true },
      { name: 'notion', cask: true },
    ],
  },
  {
    id: 'terminal-power',
    name: 'Terminal Power User',
    icon: '⚡',
    description: 'Shell productivity & CLI tools',
    packages: [
      { name: 'git', cask: false },
      { name: 'neovim', cask: false },
      { name: 'tmux', cask: false },
      { name: 'ripgrep', cask: false },
      { name: 'fd', cask: false },
      { name: 'bat', cask: false },
      { name: 'eza', cask: false },
      { name: 'fzf', cask: false },
      { name: 'zoxide', cask: false },
      { name: 'starship', cask: false },
      { name: 'htop', cask: false },
      { name: 'tldr', cask: false },
      { name: 'tree', cask: false },
      { name: 'jq', cask: false },
      { name: 'lazygit', cask: false },
      { name: 'git-delta', cask: false },
    ],
  },
  {
    id: 'rust-dev',
    name: 'Rust Developer',
    icon: '🦀',
    description: 'Rust toolchain & ecosystem',
    packages: [
      { name: 'rustup', cask: false },
      { name: 'git', cask: false },
      { name: 'gh', cask: false },
      { name: 'cmake', cask: false },
      { name: 'protobuf', cask: false },
      { name: 'llvm', cask: false },
      { name: 'sccache', cask: false },
      { name: 'ripgrep', cask: false },
      { name: 'fd', cask: false },
      { name: 'bat', cask: false },
      { name: 'hyperfine', cask: false },
      { name: 'tokei', cask: false },
      { name: 'visual-studio-code', cask: true },
      { name: 'iterm2', cask: true },
    ],
  },
  {
    id: 'go-dev',
    name: 'Go Developer',
    icon: '🐹',
    description: 'Go toolchain & common tools',
    packages: [
      { name: 'go', cask: false },
      { name: 'golangci-lint', cask: false },
      { name: 'protobuf', cask: false },
      { name: 'git', cask: false },
      { name: 'gh', cask: false },
      { name: 'jq', cask: false },
      { name: 'delve', cask: false },
      { name: 'grpcurl', cask: false },
      { name: 'visual-studio-code', cask: true },
      { name: 'goland', cask: true },
      { name: 'docker-desktop', cask: true },
      { name: 'iterm2', cask: true },
    ],
  },
  {
    id: 'java-dev',
    name: 'Java Developer',
    icon: '☕',
    description: 'JVM ecosystem & build tools',
    packages: [
      { name: 'openjdk', cask: false },
      { name: 'gradle', cask: false },
      { name: 'maven', cask: false },
      { name: 'git', cask: false },
      { name: 'gh', cask: false },
      { name: 'jq', cask: false },
      { name: 'intellij-idea-ce', cask: true },
      { name: 'docker-desktop', cask: true },
      { name: 'iterm2', cask: true },
    ],
  },
  {
    id: 'python-dev',
    name: 'Python Developer',
    icon: '🐍',
    description: 'Python toolchain & environment',
    packages: [
      { name: 'python@3.13', cask: false },
      { name: 'pyenv', cask: false },
      { name: 'pipx', cask: false },
      { name: 'poetry', cask: false },
      { name: 'git', cask: false },
      { name: 'gh', cask: false },
      { name: 'black', cask: false },
      { name: 'ruff', cask: false },
      { name: 'visual-studio-code', cask: true },
      { name: 'pycharm-ce', cask: true },
      { name: 'iterm2', cask: true },
    ],
  },
  {
    id: 'android-dev',
    name: 'Android Developer',
    icon: '🤖',
    description: 'Android SDK & tooling',
    packages: [
      { name: 'openjdk', cask: false },
      { name: 'gradle', cask: false },
      { name: 'git', cask: false },
      { name: 'gh', cask: false },
      { name: 'scrcpy', cask: false },
      { name: 'android-studio', cask: true },
      { name: 'iterm2', cask: true },
    ],
  },
  {
    id: 'security',
    name: 'Security / Pentesting',
    icon: '🔒',
    description: 'Security auditing & network tools',
    packages: [
      { name: 'nmap', cask: false },
      { name: 'wireshark', cask: false },
      { name: 'john', cask: false },
      { name: 'hashcat', cask: false },
      { name: 'aircrack-ng', cask: false },
      { name: 'hydra', cask: false },
      { name: 'sqlmap', cask: false },
      { name: 'nikto', cask: false },
      { name: 'gobuster', cask: false },
      { name: 'git', cask: false },
      { name: 'burp-suite', cask: true },
      { name: 'iterm2', cask: true },
    ],
  },
  {
    id: 'game-dev',
    name: 'Game Developer',
    icon: '🎮',
    description: 'Game engines & graphics tools',
    packages: [
      { name: 'git', cask: false },
      { name: 'git-lfs', cask: false },
      { name: 'cmake', cask: false },
      { name: 'sdl2', cask: false },
      { name: 'unity-hub', cask: true },
      { name: 'godot', cask: true },
      { name: 'blender', cask: true },
      { name: 'visual-studio-code', cask: true },
      { name: 'iterm2', cask: true },
    ],
  },
  {
    id: 'media',
    name: 'Media & Content',
    icon: '🎬',
    description: 'Video, audio & streaming tools',
    packages: [
      { name: 'ffmpeg', cask: false },
      { name: 'yt-dlp', cask: false },
      { name: 'imagemagick', cask: false },
      { name: 'obs', cask: true },
      { name: 'vlc', cask: true },
      { name: 'handbrake', cask: true },
      { name: 'audacity', cask: true },
      { name: 'gimp', cask: true },
    ],
  },
  {
    id: 'productivity',
    name: 'Productivity',
    icon: '📋',
    description: 'Everyday Mac essentials',
    packages: [
      { name: 'raycast', cask: true },
      { name: 'rectangle', cask: true },
      { name: 'notion', cask: true },
      { name: 'slack', cask: true },
      { name: 'spotify', cask: true },
      { name: '1password', cask: true },
      { name: 'the-unarchiver', cask: true },
      { name: 'appcleaner', cask: true },
    ],
  },
  {
    id: 'ai-ml',
    name: 'AI / Machine Learning',
    icon: '🧠',
    description: 'ML frameworks & GPU tools',
    packages: [
      { name: 'python@3.13', cask: false },
      { name: 'pyenv', cask: false },
      { name: 'pipx', cask: false },
      { name: 'cmake', cask: false },
      { name: 'protobuf', cask: false },
      { name: 'git', cask: false },
      { name: 'git-lfs', cask: false },
      { name: 'jupyterlab', cask: false },
      { name: 'visual-studio-code', cask: true },
      { name: 'docker-desktop', cask: true },
    ],
  },
  {
    id: 'react-dev',
    name: 'React Developer',
    icon: '⚛️',
    description: 'React & ecosystem tools',
    packages: [
      { name: 'node', cask: false },
      { name: 'git', cask: false },
      { name: 'gh', cask: false },
      { name: 'pnpm', cask: false },
      { name: 'yarn', cask: false },
      { name: 'typescript', cask: false },
      { name: 'jq', cask: false },
      { name: 'visual-studio-code', cask: true },
      { name: 'iterm2', cask: true },
      { name: 'google-chrome', cask: true },
      { name: 'firefox', cask: true },
      { name: 'figma', cask: true },
    ],
  },
  {
    id: 'vue-dev',
    name: 'Vue Developer',
    icon: '💚',
    description: 'Vue & Vite ecosystem',
    packages: [
      { name: 'node', cask: false },
      { name: 'git', cask: false },
      { name: 'gh', cask: false },
      { name: 'pnpm', cask: false },
      { name: 'yarn', cask: false },
      { name: 'typescript', cask: false },
      { name: 'jq', cask: false },
      { name: 'visual-studio-code', cask: true },
      { name: 'iterm2', cask: true },
      { name: 'google-chrome', cask: true },
      { name: 'firefox', cask: true },
      { name: 'figma', cask: true },
    ],
  },
  {
    id: 'angular-dev',
    name: 'Angular Developer',
    icon: '🅰️',
    description: 'Angular CLI & tooling',
    packages: [
      { name: 'node', cask: false },
      { name: 'git', cask: false },
      { name: 'gh', cask: false },
      { name: 'pnpm', cask: false },
      { name: 'yarn', cask: false },
      { name: 'typescript', cask: false },
      { name: 'jq', cask: false },
      { name: 'visual-studio-code', cask: true },
      { name: 'iterm2', cask: true },
      { name: 'google-chrome', cask: true },
      { name: 'firefox', cask: true },
      { name: 'figma', cask: true },
    ],
  },
  {
    id: 'svelte-dev',
    name: 'Svelte Developer',
    icon: '🔥',
    description: 'SvelteKit & Vite ecosystem',
    packages: [
      { name: 'node', cask: false },
      { name: 'git', cask: false },
      { name: 'gh', cask: false },
      { name: 'pnpm', cask: false },
      { name: 'yarn', cask: false },
      { name: 'typescript', cask: false },
      { name: 'jq', cask: false },
      { name: 'visual-studio-code', cask: true },
      { name: 'iterm2', cask: true },
      { name: 'google-chrome', cask: true },
      { name: 'firefox', cask: true },
      { name: 'figma', cask: true },
    ],
  },
  {
    id: 'nextjs-dev',
    name: 'Next.js Developer',
    icon: '▲',
    description: 'Next.js & Vercel stack',
    packages: [
      { name: 'node', cask: false },
      { name: 'git', cask: false },
      { name: 'gh', cask: false },
      { name: 'pnpm', cask: false },
      { name: 'yarn', cask: false },
      { name: 'typescript', cask: false },
      { name: 'jq', cask: false },
      { name: 'vercel-cli', cask: false },
      { name: 'visual-studio-code', cask: true },
      { name: 'iterm2', cask: true },
      { name: 'google-chrome', cask: true },
      { name: 'figma', cask: true },
      { name: 'docker-desktop', cask: true },
    ],
  },
  {
    id: 'nuxt-dev',
    name: 'Nuxt Developer',
    icon: '💚',
    description: 'Nuxt & Nitro stack',
    packages: [
      { name: 'node', cask: false },
      { name: 'git', cask: false },
      { name: 'gh', cask: false },
      { name: 'pnpm', cask: false },
      { name: 'yarn', cask: false },
      { name: 'typescript', cask: false },
      { name: 'jq', cask: false },
      { name: 'visual-studio-code', cask: true },
      { name: 'iterm2', cask: true },
      { name: 'google-chrome', cask: true },
      { name: 'firefox', cask: true },
      { name: 'figma', cask: true },
      { name: 'docker-desktop', cask: true },
    ],
  },
  {
    id: 'remix-dev',
    name: 'Remix Developer',
    icon: '💿',
    description: 'Remix & React Router stack',
    packages: [
      { name: 'node', cask: false },
      { name: 'git', cask: false },
      { name: 'gh', cask: false },
      { name: 'pnpm', cask: false },
      { name: 'yarn', cask: false },
      { name: 'typescript', cask: false },
      { name: 'jq', cask: false },
      { name: 'visual-studio-code', cask: true },
      { name: 'iterm2', cask: true },
      { name: 'google-chrome', cask: true },
      { name: 'firefox', cask: true },
      { name: 'docker-desktop', cask: true },
    ],
  },
  {
    id: 'solidjs-dev',
    name: 'SolidJS Developer',
    icon: '💙',
    description: 'SolidJS & Vite ecosystem',
    packages: [
      { name: 'node', cask: false },
      { name: 'git', cask: false },
      { name: 'gh', cask: false },
      { name: 'pnpm', cask: false },
      { name: 'yarn', cask: false },
      { name: 'typescript', cask: false },
      { name: 'jq', cask: false },
      { name: 'visual-studio-code', cask: true },
      { name: 'iterm2', cask: true },
      { name: 'google-chrome', cask: true },
      { name: 'firefox', cask: true },
    ],
  },
  {
    id: 'ember-dev',
    name: 'Ember Developer',
    icon: '🐹',
    description: 'Ember.js & CLI tools',
    packages: [
      { name: 'node', cask: false },
      { name: 'git', cask: false },
      { name: 'gh', cask: false },
      { name: 'pnpm', cask: false },
      { name: 'yarn', cask: false },
      { name: 'typescript', cask: false },
      { name: 'watchman', cask: false },
      { name: 'visual-studio-code', cask: true },
      { name: 'iterm2', cask: true },
      { name: 'google-chrome', cask: true },
      { name: 'firefox', cask: true },
    ],
  },
  {
    id: 'rails-dev',
    name: 'Ruby on Rails',
    icon: '💎',
    description: 'Rails & Ruby ecosystem',
    packages: [
      { name: 'ruby', cask: false },
      { name: 'rbenv', cask: false },
      { name: 'git', cask: false },
      { name: 'gh', cask: false },
      { name: 'postgresql@16', cask: false },
      { name: 'redis', cask: false },
      { name: 'sqlite', cask: false },
      { name: 'imagemagick', cask: false },
      { name: 'jq', cask: false },
      { name: 'visual-studio-code', cask: true },
      { name: 'iterm2', cask: true },
      { name: 'docker-desktop', cask: true },
    ],
  },
  {
    id: 'django-dev',
    name: 'Django Developer',
    icon: '🐍',
    description: 'Django & Python web stack',
    packages: [
      { name: 'python@3.13', cask: false },
      { name: 'pyenv', cask: false },
      { name: 'pipx', cask: false },
      { name: 'poetry', cask: false },
      { name: 'git', cask: false },
      { name: 'gh', cask: false },
      { name: 'postgresql@16', cask: false },
      { name: 'redis', cask: false },
      { name: 'jq', cask: false },
      { name: 'visual-studio-code', cask: true },
      { name: 'iterm2', cask: true },
      { name: 'docker-desktop', cask: true },
    ],
  },
  {
    id: 'flask-dev',
    name: 'Flask Developer',
    icon: '🧪',
    description: 'Flask & Python microservices',
    packages: [
      { name: 'python@3.13', cask: false },
      { name: 'pyenv', cask: false },
      { name: 'pipx', cask: false },
      { name: 'poetry', cask: false },
      { name: 'git', cask: false },
      { name: 'gh', cask: false },
      { name: 'redis', cask: false },
      { name: 'jq', cask: false },
      { name: 'httpie', cask: false },
      { name: 'visual-studio-code', cask: true },
      { name: 'iterm2', cask: true },
      { name: 'docker-desktop', cask: true },
    ],
  },
  {
    id: 'fastapi-dev',
    name: 'FastAPI Developer',
    icon: '⚡',
    description: 'FastAPI & async Python',
    packages: [
      { name: 'python@3.13', cask: false },
      { name: 'pyenv', cask: false },
      { name: 'pipx', cask: false },
      { name: 'poetry', cask: false },
      { name: 'git', cask: false },
      { name: 'gh', cask: false },
      { name: 'postgresql@16', cask: false },
      { name: 'redis', cask: false },
      { name: 'jq', cask: false },
      { name: 'httpie', cask: false },
      { name: 'visual-studio-code', cask: true },
      { name: 'iterm2', cask: true },
      { name: 'docker-desktop', cask: true },
    ],
  },
  {
    id: 'express-dev',
    name: 'Express.js Developer',
    icon: '🟢',
    description: 'Express & Node.js backend',
    packages: [
      { name: 'node', cask: false },
      { name: 'git', cask: false },
      { name: 'gh', cask: false },
      { name: 'pnpm', cask: false },
      { name: 'yarn', cask: false },
      { name: 'typescript', cask: false },
      { name: 'redis', cask: false },
      { name: 'postgresql@16', cask: false },
      { name: 'jq', cask: false },
      { name: 'httpie', cask: false },
      { name: 'visual-studio-code', cask: true },
      { name: 'iterm2', cask: true },
      { name: 'docker-desktop', cask: true },
      { name: 'postman', cask: true },
    ],
  },
  {
    id: 'spring-dev',
    name: 'Spring Boot',
    icon: '🍃',
    description: 'Spring & JVM backend',
    packages: [
      { name: 'openjdk', cask: false },
      { name: 'gradle', cask: false },
      { name: 'maven', cask: false },
      { name: 'git', cask: false },
      { name: 'gh', cask: false },
      { name: 'postgresql@16', cask: false },
      { name: 'redis', cask: false },
      { name: 'jq', cask: false },
      { name: 'httpie', cask: false },
      { name: 'intellij-idea-ce', cask: true },
      { name: 'docker-desktop', cask: true },
      { name: 'iterm2', cask: true },
    ],
  },
  {
    id: 'dotnet-dev',
    name: '.NET Developer',
    icon: '🟣',
    description: 'ASP.NET & C# backend',
    packages: [
      { name: 'dotnet', cask: false },
      { name: 'git', cask: false },
      { name: 'gh', cask: false },
      { name: 'postgresql@16', cask: false },
      { name: 'redis', cask: false },
      { name: 'jq', cask: false },
      { name: 'visual-studio-code', cask: true },
      { name: 'docker-desktop', cask: true },
      { name: 'iterm2', cask: true },
    ],
  },
  {
    id: 'laravel-dev',
    name: 'Laravel Developer',
    icon: '🔴',
    description: 'Laravel & PHP ecosystem',
    packages: [
      { name: 'php', cask: false },
      { name: 'composer', cask: false },
      { name: 'git', cask: false },
      { name: 'gh', cask: false },
      { name: 'postgresql@16', cask: false },
      { name: 'redis', cask: false },
      { name: 'sqlite', cask: false },
      { name: 'jq', cask: false },
      { name: 'visual-studio-code', cask: true },
      { name: 'iterm2', cask: true },
      { name: 'docker-desktop', cask: true },
    ],
  },
  {
    id: 'phoenix-dev',
    name: 'Phoenix / Elixir',
    icon: '🔮',
    description: 'Phoenix & Elixir stack',
    packages: [
      { name: 'elixir', cask: false },
      { name: 'erlang', cask: false },
      { name: 'git', cask: false },
      { name: 'gh', cask: false },
      { name: 'postgresql@16', cask: false },
      { name: 'redis', cask: false },
      { name: 'jq', cask: false },
      { name: 'visual-studio-code', cask: true },
      { name: 'iterm2', cask: true },
      { name: 'docker-desktop', cask: true },
    ],
  },
  {
    id: 'gin-dev',
    name: 'Gin / Go Backend',
    icon: '🍸',
    description: 'Gin & Go web services',
    packages: [
      { name: 'go', cask: false },
      { name: 'golangci-lint', cask: false },
      { name: 'git', cask: false },
      { name: 'gh', cask: false },
      { name: 'postgresql@16', cask: false },
      { name: 'redis', cask: false },
      { name: 'protobuf', cask: false },
      { name: 'jq', cask: false },
      { name: 'grpcurl', cask: false },
      { name: 'visual-studio-code', cask: true },
      { name: 'docker-desktop', cask: true },
      { name: 'iterm2', cask: true },
    ],
  },
  {
    id: 'actix-dev',
    name: 'Actix / Rust Backend',
    icon: '🦀',
    description: 'Actix-web & Rust services',
    packages: [
      { name: 'rustup', cask: false },
      { name: 'git', cask: false },
      { name: 'gh', cask: false },
      { name: 'postgresql@16', cask: false },
      { name: 'redis', cask: false },
      { name: 'protobuf', cask: false },
      { name: 'cmake', cask: false },
      { name: 'jq', cask: false },
      { name: 'visual-studio-code', cask: true },
      { name: 'docker-desktop', cask: true },
      { name: 'iterm2', cask: true },
    ],
  },
]

export function usePresets() {
  return { presets }
}
